# Form implementation generated from reading ui file 'c:\Users\13287\Documents\GitHub\os_lab\ui\ProcessUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import (QApplication, QHeaderView, QSizePolicy, QTableWidget,
    QTableWidgetItem, QWidget)


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 600)
        self.NavigationPanel = NavigationPanel(parent=Form)
        self.NavigationPanel.setGeometry(QtCore.QRect(0, 0, 50, 600))
        self.NavigationPanel.setProperty("menu", False)
        self.NavigationPanel.setObjectName("NavigationPanel")
        # self.NavigationPanel.addItem(routeKey="666",icon="None",text="666",onClick=None)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
from qfluentwidgets import NavigationPanel

class ProcessUI():
    def __init__(self) -> None:
        self.window = QWidget()
        self.ui = Ui_Form()
        self.ui.setupUi(self.window)

if __name__ == "__main__":
    app = QApplication([])
    window = ProcessUI()
    window.window.show()
    
    app.exec()