# Form implementation generated from reading ui file 'c:\Users\13287\Documents\GitHub\os_lab\ui\DeviceAdd.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DeviceAdd(object):
    def setupUi(self, DeviceAdd):
        DeviceAdd.setObjectName("DeviceAdd")
        DeviceAdd.resize(400, 300)
        self.TrueAddButton = PushButton(parent=DeviceAdd)
        self.TrueAddButton.setGeometry(QtCore.QRect(80, 220, 102, 32))
        self.TrueAddButton.setObjectName("TrueAddButton")
        self.LineEdit = LineEdit(parent=DeviceAdd)
        self.LineEdit.setGeometry(QtCore.QRect(140, 70, 128, 33))
        self.LineEdit.setObjectName("LineEdit")
        self.LineEdit_2 = LineEdit(parent=DeviceAdd)
        self.LineEdit_2.setGeometry(QtCore.QRect(140, 140, 128, 33))
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.DevTypelabel = QtWidgets.QLabel(parent=DeviceAdd)
        self.DevTypelabel.setGeometry(QtCore.QRect(70, 80, 71, 20))
        self.DevTypelabel.setObjectName("DevTypelabel")
        self.DevIDlabel = QtWidgets.QLabel(parent=DeviceAdd)
        self.DevIDlabel.setGeometry(QtCore.QRect(80, 150, 41, 16))
        self.DevIDlabel.setObjectName("DevIDlabel")
        self.NotAddButton = PushButton(parent=DeviceAdd)
        self.NotAddButton.setGeometry(QtCore.QRect(220, 220, 102, 32))
        self.NotAddButton.setObjectName("NotAddButton")

        self.retranslateUi(DeviceAdd)
        QtCore.QMetaObject.connectSlotsByName(DeviceAdd)

    def retranslateUi(self, DeviceAdd):
        _translate = QtCore.QCoreApplication.translate
        DeviceAdd.setWindowTitle(_translate("DeviceAdd", "Form"))
        self.TrueAddButton.setText(_translate("DeviceAdd", "确认添加"))
        self.DevTypelabel.setText(_translate("DeviceAdd", "设备类型"))
        self.DevIDlabel.setText(_translate("DeviceAdd", "设备ID"))
        self.NotAddButton.setText(_translate("DeviceAdd", "取消添加"))
from qfluentwidgets import LineEdit, PushButton
