# Form implementation generated from reading ui file 'c:\Users\13287\Documents\GitHub\os_lab\ui\DeviceManager.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DeviceManager(object):
    def setupUi(self, DeviceManager):
        DeviceManager.setObjectName("DeviceManager")
        DeviceManager.resize(500, 600)
        self.AddDeviceButton = PushButton(parent=DeviceManager)
        self.AddDeviceButton.setGeometry(QtCore.QRect(90, 560, 102, 32))
        self.AddDeviceButton.setObjectName("AddDeviceButton")
        self.DelDeviceButton = PushButton(parent=DeviceManager)
        self.DelDeviceButton.setGeometry(QtCore.QRect(290, 560, 102, 32))
        self.DelDeviceButton.setObjectName("DelDeviceButton")
        self.TableView = TableView(parent=DeviceManager)
        self.TableView.setGeometry(QtCore.QRect(0, 0, 500, 550))
        self.TableView.setObjectName("TableView")

        self.retranslateUi(DeviceManager)
        QtCore.QMetaObject.connectSlotsByName(DeviceManager)

    def retranslateUi(self, DeviceManager):
        _translate = QtCore.QCoreApplication.translate
        DeviceManager.setWindowTitle(_translate("DeviceManager", "Form"))
        self.AddDeviceButton.setText(_translate("DeviceManager", "添加设备"))
        self.DelDeviceButton.setText(_translate("DeviceManager", "删除设备"))
from qfluentwidgets import PushButton, TableView
